print("Less than: 4 < 5")
print(4 < 5)
print("Greater than: 7 > 8")
print(7 > 8)
print("Less than or equal to: 5 <= 9")
print(5 <= 9)
print("Greater than or equal to: 1 >= 9")
print(1 >= 9)
print("Is equal to: 4 == 4")
print(4 == 4)
print("Is NOT equal to: 7 != 7")
print(7 != 7)
